### ISSUE TITLE
Sesión de requisitado

### ISSUE THREAD

**Issue by celiabecerril** [mmasias/24-25-IdSw1-SDR#2]
Buenas tardes, otros grupos han comentado que ya tienen fecha para reunión. ¿Dónde podemos ver la fecha y hora de la nuestra?

**Comment by mmasias** [comment]
> Buenas tardes, otros grupos han comentado que ya tienen fecha para reunión. ¿Dónde podemos ver la fecha y hora de la nuestra?

@celiabecerril : la reunión está pendiente de definición por parte del cliente. Espero entre hoy y mañana dejarla definida.
